# Generated by Django 4.1 on 2024-07-12 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0006_alter_fotografia_publicada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('NEBULOSA', 'Nebulosa'), ('ESTRELA', 'Estrela'), ('GALÁXIA', 'Galáxia'), ('PLANETA', 'Planeta'), ('SATELITE', 'Satélite'), ('ASTEROIDE', 'Asteroide'), ('COMETA', 'Cometa')], default='', max_length=100),
        ),
    ]
