# Generated by Django 4.1 on 2024-07-15 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0009_alter_fotografia_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='cloudinary_public_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
