# Generated by Django 4.1 on 2024-07-15 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0010_fotografia_cloudinary_public_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotografia',
            old_name='cloudinary_public_id',
            new_name='public_id',
        ),
    ]
