# Generated by Django 4.1 on 2024-07-15 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0011_rename_cloudinary_public_id_fotografia_public_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotografia',
            old_name='public_id',
            new_name='cloudinary_public_id',
        ),
    ]
